# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.0

pipelines:
  default:
    - step:
        name: Test
        caches:
          - node
        script: # 
          - npm install
          - npm test
  pull-requests:
    '**':
      - step:
          name: PR Build Check
          caches:
            - node
          script:
            - npm build
